/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/BatchDailyTasks': RouteRecordInfo<'/BatchDailyTasks', '/BatchDailyTasks', Record<never, never>, Record<never, never>>,
    '/card-flip-ops/AutomationControlPanel': RouteRecordInfo<'/card-flip-ops/AutomationControlPanel', '/card-flip-ops/AutomationControlPanel', Record<never, never>, Record<never, never>>,
    '/card-flip-ops/AutotradePanel': RouteRecordInfo<'/card-flip-ops/AutotradePanel', '/card-flip-ops/AutotradePanel', Record<never, never>, Record<never, never>>,
    '/card-flip-ops/CardFlipOpsPage': RouteRecordInfo<'/card-flip-ops/CardFlipOpsPage', '/card-flip-ops/CardFlipOpsPage', Record<never, never>, Record<never, never>>,
    '/card-flip-ops/ExecutionRetryPanel': RouteRecordInfo<'/card-flip-ops/ExecutionRetryPanel', '/card-flip-ops/ExecutionRetryPanel', Record<never, never>, Record<never, never>>,
    '/card-flip-ops/OpsOverviewHeader': RouteRecordInfo<'/card-flip-ops/OpsOverviewHeader', '/card-flip-ops/OpsOverviewHeader', Record<never, never>, Record<never, never>>,
    '/card-flip-ops/TradeDataTabs': RouteRecordInfo<'/card-flip-ops/TradeDataTabs', '/card-flip-ops/TradeDataTabs', Record<never, never>, Record<never, never>>,
    '/CardFlipModeDashboard': RouteRecordInfo<'/CardFlipModeDashboard', '/CardFlipModeDashboard', Record<never, never>, Record<never, never>>,
    '/Changelog': RouteRecordInfo<'/Changelog', '/Changelog', Record<never, never>, Record<never, never>>,
    '/DailyTasks': RouteRecordInfo<'/DailyTasks', '/DailyTasks', Record<never, never>, Record<never, never>>,
    '/Dashboard': RouteRecordInfo<'/Dashboard', '/Dashboard', Record<never, never>, Record<never, never>>,
    '/GameFeatures': RouteRecordInfo<'/GameFeatures', '/GameFeatures', Record<never, never>, Record<never, never>>,
    '/GameRoles': RouteRecordInfo<'/GameRoles', '/GameRoles', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/Profile': RouteRecordInfo<'/Profile', '/Profile', Record<never, never>, Record<never, never>>,
    '/Register': RouteRecordInfo<'/Register', '/Register', Record<never, never>, Record<never, never>>,
    '/TokenImport/': RouteRecordInfo<'/TokenImport/', '/TokenImport', Record<never, never>, Record<never, never>>,
    '/TokenImport/bin': RouteRecordInfo<'/TokenImport/bin', '/TokenImport/bin', Record<never, never>, Record<never, never>>,
    '/TokenImport/manual': RouteRecordInfo<'/TokenImport/manual', '/TokenImport/manual', Record<never, never>, Record<never, never>>,
    '/TokenImport/url': RouteRecordInfo<'/TokenImport/url', '/TokenImport/url', Record<never, never>, Record<never, never>>,
  }
}
